server:
  port: 6666
spring:
  application:
    name: cloud-gateway-6666
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true # 请求服务是小写的时候改成true（默认为false轻微服务必须是大写）
      routes:
        - id: cloud-provider-9001 #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-provider-9001  #匹配后提供服务的路由地址
          order: 9001
          predicates:
            - Path=/user/getUser/**   #断言,路径相匹配的进行路由

#        - id: cloud-consumer-openfeign-91
#          uri: lb://cloud-consumer-openfeign-91
#          predicates:
#            - Path=/lb/**   #断言,路径相匹配的进行路由
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址
